# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: 261P Assignment4

on:
  #event to trigger workflow
  push:
    branches: [ "master" ]
jobs:
  build:
    #set running environment
    runs-on: ubuntu-latest

    #operations
    steps:
    - uses: actions/checkout@v3

      # set the version of JDK
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

      # in order to increase efficiency, Cache maven dependencies
    - uses: actions/cache@v1
      with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # set the version of MySQL
    - name: Set up MySQL
      uses: calxus/mysql-deploy-action@v1
      with:
        DATABASE_PORT: '3306'
        DATABASE_NAME: 'mall'
        DATABASE_USERNAME: 'root'
        DATABASE_PASSWORD: '1234'
        DATABASE_SCRIPT: './document/sql/mall.sql'
        
      # set the redis
    - uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: "6.x"
    - run: redis-cli ping

      # run all test cases in project
    - name: Test
      run: mvn clean test
      
