# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: 261P Assignment4

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Setup redis
      uses: redis/redis-action@1.1.0
      with:
        version: 5.0.14
    - name: Setup mysql
      uses: mysql/mysql-action@v1
      with:
        host port: 3306
        container port: 3306
        character set server: utf-8
        mysql version: 8.0.31
        mysql database: jdbc:mysql://localhost:3306/mall
        mysql user: root
        mysql password: 1234
    - name: Run unit test
      run: mvn clean test 
